### ISSUE TITLE
Exception thrown when moving issue

### ISSUE THREAD

**Issue by sergioc** [Particular/PBot#68]
When issuing the command `move issue website.frontent#375 to developereducation`, the following exception is thrown:

```
System.AggregateException: One or more errors occurred. ---> Octokit.NotFoundException: Not Found
  at Octokit.Connection.HandleErrors(IResponse response) in c:\nsb\octokit.net\Octokit\Http\Connection.cs:line 464
  at Octokit.Connection.<RunRequest>d__23.MoveNext() in c:\nsb\octokit.net\Octokit\Http\Connection.cs:line 446
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
  at Octokit.Connection.<Run>d__1f`1.MoveNext() in c:\nsb\octokit.net\Octokit\Http\Connection.cs:line 436
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
  at Octokit.ApiConnection.<Get>d__0`1.MoveNext() in c:\nsb\octokit.net\Octokit\Http\ApiConnection.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
  at PBot.Issues.IssueUtility.<Transfer>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at PBot.Issues.MoveIssue.<Execute>d__1.MoveNext()
  --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
  at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
  at PBot.BotCommand.<Register>b__3_0(IResponse`1 msg)
---> (Inner Exception #0) Octokit.NotFoundException: Not Found
  at Octokit.Connection.HandleErrors(IResponse response) in c:\nsb\octokit.net\Octokit\Http\Connection.cs:line 464
  at Octokit.Connection.<RunRequest>d__23.MoveNext() in c:\nsb\octokit.net\Octokit\Http\Connection.cs:line 446
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
  at Octokit.Connection.<Run>d__1f`1.MoveNext() in c:\nsb\octokit.net\Octokit\Http\Connection.cs:line 436
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
  at Octokit.ApiConnection.<Get>d__0`1.MoveNext() in c:\nsb\octokit.net\Octokit\Http\ApiConnection.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
  at PBot.Issues.IssueUtility.<Transfer>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at PBot.Issues.MoveIssue.<Execute>d__1.MoveNext()<---
```

**Comment by adamralph** [comment]
@sergioc "frontent" - should be "frontend"

**Comment by sergioc** [comment]
doh!
